# markdownlint configuration
# https://github.com/DavidAnson/markdownlint

# Let prettier/formatters handle line length in the future.
MD013: false

# Allow inline HTML in docs when needed (e.g., badges).
MD033: false

# Allow duplicate headings (common in READMEs/CHANGELOGs) in different sections.
MD024:
  siblings_only: true

# Enforce fenced code blocks and consistent style.
MD046:
  style: fenced
